$('body').addClass('variation');
$('#content > section.pushes').prepend($('#content > section.pushes > div').clone().addClass('new-section'));
$('#content > section.pushes > div.container.new-section > div:nth-child(1) > i').replaceWith('<img src="//cdn.optimizely.com/img/72220526/db57a266a96f415d9b74cef94b4f7496.png">');
$('#content > section.pushes > div.container.new-section > div.push.invert > i').replaceWith('<img class="penny" src="//cdn.optimizely.com/img/72220526/bf0909a26041425b9ec2f7b6df389ad6.png">');
$('#content > section.pushes > div.container.new-section > div:nth-child(3) > i').replaceWith('<img src="https://northamericanspine.com/wp-content/themes/north-american-spine/landing/webinar/img/Circle-96-Percent.png">');
$('#content > section.pushes > div.container.new-section > div:nth-child(1) > div.body > h3').text('100% of our partner physicians are board certified');
$('#content > section.pushes > div.container.new-section > div:nth-child(1) > div.body > p').remove();
$('#content > section.pushes > div.container.new-section > div.push.invert > div.body > h3').text('Outpatient procedures with incisions smaller than a penny');
$('#content > section.pushes > div.container.new-section > div.push.invert > div.body > p').remove();
$('#content > section.pushes > div.container.new-section > div:nth-child(3) > div.body > h3').text('96% of our patients would recommend their doctor to a friend');
$('#content > section.pushes > div.container.new-section > div:nth-child(3) > div.body > p').remove();
$('#content > section.pushes > div.container.new-section > div:nth-child(1) > div.btn-center').remove();
$('#content > section.pushes > div.container.new-section > div.push.invert > div.btn-center').remove();
$('#content > section.pushes > div.container.new-section > div:nth-child(3) > div.btn-center').remove();
$('#content > section.pushes > div.container.new-section').prepend('<div class="body"><h3 class="title">Our Experienced Physicians are Specialty Trained in Minimally Invasive Techniques<h3></body>');
$('#content > section.pushes > div.container.new-section').wrap('<section></section>');
$('#content > section.cities-section.visible-xs.visible-sm').clone().insertAfter('.new-section');
$('#content > main').clone().insertAfter('#content > section.pushes > section > section');
$('#content > section.mid-section > div > div.benefits-of.col-sm-8.visible-md.visible-lg > ul > li:nth-child(6) > div > p').text('Thanks to our highly trained doctors, 96% of our patients would recommend their physician.');